# Welcome to Jekyll!
# 
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: <b style='color :#007bff; font-weight:900!important;'>Jori</b><span>gamy</span>
email: lantoniotrento@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Jorigamy is a porting of <a href="https://designrevision.com/download/shards" rel="nofollow">Shards UI toolkit</a> a bootstrap4 starter template intalled for Jekyll static website generator.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jorigamy.github.io" # the base hostname & protocol for your site, e.g. http://example.com

excerpt_separator: "<!--more-->"

footer-calltoaction: <div class="container my-5"><div class="py-5"><div class="text-center"><h1>🛠</h1><h2 class="text-white">Build Something!</h2><p class="text-muted col-lg-8 col-md-10 ml-auto mr-auto lead">What are you waiting for? <b><u>Go ahead and build something!</u></b> Can't wait to see what you come up with! If you like Jorigamy, make sure you share it with your friends too!</p></div><div class="share d-table ml-auto mr-auto mt-5 lead"><a style="background:#00aced!important;" href="https://twitter.com/intent/tweet?url=https://jorigamy.github.io&text=I%27m+in+love+with+Jorigamy%2C+a+free+Jekyll+Theme+by+%40@lantoniotrento+%23ui+%23design+%23free+%23bootstrap" class="btn btn-pill btn-primary mr-4" title="Share Shards on Twitter"><i class="fa fa-twitter mr-1"></i> Share on Twitter</a> <a style="background: #3b5998!important;" href="https://www.facebook.com/sharer/sharer.php?u=https://jorigamy.github.io" class="btn btn-pill btn-primary mr-4" title="Share on Facebook"><i class="fa fa-facebook mr-1"></i> Share on Facebook</a> <a style="background: #0077B5!important;" href="https://www.linkedin.com/shareArticle?mini=true&title=Jorigamy+%E2%80%94+A+free+and+modern+Jekyll+Theme+for+create+landingàpages&url=https://jorigamy.github.io" class="btn btn-pill btn-primary mr-4" title="Share on LinkedIn"><i class="fa fa-linkedin mr-1"></i> Share on LinkedIn</a></div><br /><br /><br /><br /><br /><br /><div class="text-center"><h2 class="text-white">And then.. Help by little actions! <button style="margin-left: 1em" type="button" class="btn btn-lg btn-success" data-toggle="modal" data-target="#donate"><i class="fa fa-bitcoin mr-1 animated infinite tada"></i> Donate<!--span class="animated infinite flash">Donate</span--></button></h2></div></div></div>

footer: <p class="text-muted text-center p-0 mb-4 lead">&copy; Copyright {{ 'now' | date: "%Y" }} — <a href="https://lantoniotrento.github.io" target="_blank"> 🧔🏻 Antonio Trento</a> - UI Kit 🏗 by <a href="https://designrevision.com" rel="nofollow">designrevision</a>- Image 🏔 by <a href="https://freepik.com" rel="nofollow">freepik</a></p><p class="text-muted text-center p-0 mb-4 lead">Report me a <a style="margin-bottom: -15px" class="github-button" href="https://github.com/jorigamy/jorigamy.github.io/issues" data-show-count="true" aria-label="Issue jorigamy/jorigamy.github.io on GitHub">Issue</a> or, if you like 🤙 <a class="twitter-share-button" href="https://twitter.com/share" data-size="large" data-text="I'm in love with Jorigamy, a free Jekyll theme" data-url="https://jorigamy.github.io" data-hashtags="jekyll,ui,design,web,bootstrap" data-via="lantoniotrento">Tweet </a></p><div class="social d-table ml-auto mr-auto"><a class="twitter mx-3 h4" href="https://twitter.com/{{ site.author.twitter }}" target="_blank"><i class="fa fa-twitter"></i> <span class="sr-only">View our Twitter Profile</span> </a><a class="twitter mx-3 h4" href="https://www.linkedin.com/in/{{ site.author.linkedin }}" target="_blank"><i class="fa fa-linkedin"></i> <span class="sr-only">Connect with me on LinkedIn</span> </a><a class="facebook mx-3 h4" href="https://www.facebook.com/{{ site.author.facebook }}" target="_blank"><i class="fa fa-facebook"></i> <span class="sr-only">View our Facebook Profile <span></span></span></a> <a class="github mx-3 h4" href="https://github.com/{{ site.author.github }}" target="_blank"><i class="fa fa-github"></i> <span class="sr-only">View our GitHub Profile</span></a> <!-- Place this tag where you want the button to render. --></div>

#Permalinks

#permalink: /:title/
#permalink: /:categories/:title/
#permalink: /:year/:month/:day/:title.html

#Finding solution for pagination, now is disabled

# paginate: 6

logo: /assets/images/shard-1-5x-3.png
favicon: flavicon.png
navbar-logo: jorigamy-logo.svg

author :
  name : Antonio Trento
  email : lantoniotrento@gmail.com
  github : jorigamy/jorigamy.github.io
  twitter : lantoniotrento
  facebook: lantoniotrento
  linkedin: antoniotrento
  instagram: lantoniotrento
  pinterest: antoniotrento
  google: https://plus.google.com/u/0/b/114870349902392641766/105909498949786982602
  feedburner :

google :
    tracking_id : 'UA-109407288-1' # Id google analitics
    optimize_id : 'GTM-MPKVJB9' # I'id di google optimize per A/B Testing
    tagmanager_id: 'GTM-5VNXBR4' # id di google tag manager
    ad_client: 'ca-pub-9204963049240271' # id google ADsense (to edit other id's of google ADsense go to /_includes/JB/ads-block-html )

disqus :
    short_name : blog-antonio-trento
    # how to use
    #      {% if site.disqus.short_name %}
    #        {% include JB/disqus.html %}
    #      {% endif %}


# data for jekyll-seo-tags plugins
social:
  name: lantoniotrento
  links:
    - https://twitter.com/lantoniotrento
    - https://www.facebook.com/lantoniotrento
    - https://www.linkedin.com/in/antoniotrento
    - https://plus.google.com/u/0/b/114870349902392641766/105909498949786982602
    - https://github.com/jorigamy/jorigamy.github.io
    - https://keybase.io/antoniotrento
twitter:
  username: lantoniotrento

facebook:
 app_id: 509727322725898 #the app id from https://developers.facebook.com/
 admins: 1010094929028825 #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
 publisher: 1010094929028825 #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'


algolia:
  application_id: 'GU8HT2BGPU'
  index_name:     'your_index_name' # I'm looking to understand how it can be set the index_name of agolia https://www.algolia.com/apps/GU8HT2BGPU/dashboard and https://community.algolia.com/jekyll-algolia/getting-started.html

cloudinary:
  cloud_name: officialtrento #  NOT WORK FOR NOW from the cloudinary-jekyll plugin guide https://nhoizey.github.io/jekyll-cloudinary/#installation
  presets:
  default:
    min_width: 320
    max_width: 1600
    fallback_max_width: 800
    steps: 5
    sizes: "(min-width: 50rem) 50rem, 90vw"

# Build settings
markdown: kramdown

#theme: minima
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-seo-tag

#gems:
#  - amp-jekyll

#ampdir: amp



# Gallery section (https://jorigami.github.io/gallery)

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url: https://facebook.com/lantoniotrento
github_url:
gitlab_url:
googleplus_url: https://plus.google.com/u/0/b/114870349902392641766/105909498949786982602
instagram_url: https://instagram.com/lantoniotrento
linkedin_url: https://linkedin.com/in/antoniotrento
pinterest_url: https://pinterest.com/antoniotrento
slack_url:
twitter_url: https://twitter.com/lantoniotrento




gallery-title: Jorigamy
gallery-description: >- # this means to ignore newlines until "baseurl:"
  The gallery section of the jorigamy blog.



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
